### PR TITLE
ENH: Update extension metadata

### PR DESCRIPTION
**Pull request by jcfr**
Consolidate extension metadata based on the corresponding s4ext file organized
in the ExtensionsIndex repository.

### CODE REVIEW

**Comment by jcfr** [comment]
Please, could this be reviewed & merged :pray:

**Comment by jcfr** [comment]
Email sent on June 12th 2024 to @Thibault-Pelletier with @lassoan in cc:

```
Subject: Help to merge https://github.com/R-Vessel-X/SlicerRVXVesselnessFilters/pull/7

Hi Thibault,

When you have a chance, we would appreciate your help to merge the following pull request:

  ENH: Update extension metadata
  https://github.com/R-Vessel-X/SlicerRVXVesselnessFilters/pull/7

Changes are trivial as they only include updates to the extension metadata.

Thanks
J-Christophe
```

**Comment by Thibault-Pelletier** [comment]
Hi @jcfr ,
Thanks for the PR!

Actually it should be the other way around. The RVXVesselnessFilters.s4ext should point to the https://github.com/R-Vessel-X/SlicerRVXVesselnessFilters/raw/main/Screenshots/RVXLogo.png file. 

We have two extensions named RVX<something> one for the liver segmentation / annotation workflow and this one which only contains vessel enhancement filter (to make it easier for users to use the filters).

**Comment by jcfr** [comment]
Thanks for the review :pray: This was an oversight and should now be fixed :ok_hand:

**Comment by Thibault-Pelletier** [comment]
Great, thanks!

**Comment by jcfr** [comment]
@Thibault-Pelletier Thanks for taking the time to follow-up :pray: :rocket:

**Pull request merged**
